export const CREATE_PURCHASE = 'CREATE_PURCHASE';
export const EDIT_PURCHASE = 'EDIT_PURCHASE';
export const DELETE_PURCHASE = 'DELETE_PURCHASE';
export const CHANGE_PLACE = 'CHANGE_PLACE';
export const CHANGE_PRICE = 'CHANGE_PRICE';