export const CREATE_PURCHASE = 'CREATE_PURCHASE';
export const CREATE_PURCHASE_SUCCESS = 'CREATE_PURCHASE_SUCCESS';
export const CREATE_PURCHASE_FAIL = 'CREATE_PURCHASE_FAIL';

export const EDIT_PURCHASE = 'EDIT_PURCHASE';
export const EDIT_PURCHASE_SUCCESS = 'EDIT_PURCHASE_SUCCESS';
export const EDIT_PURCHASE_FAIL = 'EDIT_PURCHASE_FAIL';

export const DELETE_PURCHASE = 'DELETE_PURCHASE';
export const DELETE_PURCHASE_SUCCESS = 'DELETE_PURCHASE_SUCCESS';
export const DELETE_PURCHASE_FAIL = 'DELETE_PURCHASE_FAIL';

export const GET_PURCHASES = 'GET_PURCHASES';
export const GET_PURCHASES_SUCCESS = 'GET_PURCHASES_SUCCESS';
export const GET_PURCHASES_FAIL = 'GET_PURCHASES_FAIL';

export const CHANGE_PLACE = 'CHANGE_PLACE';
export const CHANGE_PRICE = 'CHANGE_PRICE';
